server:
  port: 8181
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vue?serverTimezone=UTC
    username: root
    password: 550098879
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true      #打印sql语句
    properties:
      hibernate:
        format_sql: true  #格式化
